# bitbucket-pipelines.yml

pipelines:
  branches:
    main:
      - step:
          name: Build and Package
          image: node:18.17.0
          caches:
            - node
          script:
            - echo "Starting the build process"
            - npm ci
            - CI=false npm run build
          artifacts:
            - dist/**

      - step: &deploy
          name: Deploy to Production
          deployment: production
          <<: *deploy
          script:
            - echo "Deploying to production"
            # Use Bitbucket Pipelines secrets management for credentials
            - pipe: atlassian/ftp-deploy:0.3.1
              variables:
                USERNAME: 'tomasosho'
                PASSWORD: 'Teledensity25'
                SERVER: ftp.thebulb.africa
                REMOTE_PATH: /
                LOCAL_PATH: .next/standalone

  definitions:
    caches:
      node: ~/.npm
