# bitbucket-pipelines.yml

pipelines:
  branches:
    main:
      - step:
          name: Build and Package
          image: node:18.17.0
          caches:
            - node
          script:
            - echo "Starting the build process"
            - npm ci
            - CI=false npm run build
          artifacts:
            - .next/standalone/**

      - step: &deploy
          name: Deploy to Production
          deployment: production
          <<: *deploy
          script:
            - echo "Deploying to production"
            - pipe: atlassian/ftp-deploy:0.3.1
              variables:
                USERNAME: $BITBUCKET_USERNAME
                PASSWORD: $FTP_PASSWORD
                SERVER: ftp.thebulb.africa
                REMOTE_PATH: /
                LOCAL_PATH: .next/standalone
           
                SSH_USER: $BITBUCKET_USERNAME
                SERVER: $SSH_JUMP_HOST
                SSH_KEY: $FTP_PASSWORD
                MODE: "script"
                COMMAND: "./ansible/deploy-dev.sh"

  definitions:
    caches:
      node: ~/.npm
