export const picksData = [
    {
        id: 1,
        stackText: "Arts & Theatre",
        heading: "FunnyBone Live 2024 - Aina's Son",
        location:"Eko Hotels & Suites",
        state:"Lagos",
        date:"Jul 16, 2024",
        time:"6:00 PM",
        rating:"3.7",
        numbers:"5,274",
        sold:"26K",
        initialAmount:"5,000",
        finalAmount:"5,000,000"
    },
    {
        id: 1,
        stackText: "Arts & Theatre",
        heading: "FunnyBone Live 2024 - Aina's Son",
        location:"Eko Hotels & Suites",
        state:"Lagos",
        date:"Jul 16, 2024",
        time:"6:00 PM",
        rating:"3.7",
        numbers:"5,274",
        sold:"26K",
        initialAmount:"5,000",
        finalAmount:"5,000,000"
    },
    {
        id: 1,
        stackText: "Arts & Theatre",
        heading: "FunnyBone Live 2024 - Aina's Son",
        location:"Eko Hotels & Suites",
        state:"Lagos",
        date:"Jul 16, 2024",
        time:"6:00 PM",
        rating:"3.7",
        numbers:"5,274",
        sold:"26K",
        initialAmount:"5,000",
        finalAmount:"5,000,000"
    },
    {
        id: 1,
        stackText: "Arts & Theatre",
        heading: "FunnyBone Live 2024 - Aina's Son",
        location:"Eko Hotels & Suites",
        state:"Lagos",
        date:"Jul 16, 2024",
        time:"6:00 PM",
        rating:"3.7",
        numbers:"5,274",
        sold:"26K",
        initialAmount:"5,000",
        finalAmount:"5,000,000"
    },
    {
        id: 1,
        stackText: "Arts & Theatre",
        heading: "FunnyBone Live 2024 - Aina's Son",
        location:"Eko Hotels & Suites",
        state:"Lagos",
        date:"Jul 16, 2024",
        time:"6:00 PM",
        rating:"3.7",
        numbers:"5,274",
        sold:"26K",
        initialAmount:"5,000",
        finalAmount:"5,000,000"
    },
    {
        id: 1,
        stackText: "Arts & Theatre",
        heading: "FunnyBone Live 2024 - Aina's Son",
        location:"Eko Hotels & Suites",
        state:"Lagos",
        date:"Jul 16, 2024",
        time:"6:00 PM",
        rating:"3.7",
        numbers:"5,274",
        sold:"26K",
        initialAmount:"5,000",
        finalAmount:"5,000,000"
    },
    {
        id: 1,
        stackText: "Arts & Theatre",
        heading: "FunnyBone Live 2024 - Aina's Son",
        location:"Eko Hotels & Suites",
        state:"Lagos",
        date:"Jul 16, 2024",
        time:"6:00 PM",
        rating:"3.7",
        numbers:"5,274",
        sold:"26K",
        initialAmount:"5,000",
        finalAmount:"5,000,000"
    },
    {
        id: 1,
        stackText: "Arts & Theatre",
        heading: "FunnyBone Live 2024 - Aina's Son",
        location:"Eko Hotels & Suites",
        state:"Lagos",
        date:"Jul 16, 2024",
        time:"6:00 PM",
        rating:"3.7",
        numbers:"5,274",
        sold:"26K",
        initialAmount:"5,000",
        finalAmount:"5,000,000"
    },
    {
        id: 1,
        stackText: "Arts & Theatre",
        heading: "FunnyBone Live 2024 - Aina's Son",
        location:"Eko Hotels & Suites",
        state:"Lagos",
        date:"Jul 16, 2024",
        time:"6:00 PM",
        rating:"3.7",
        numbers:"5,274",
        sold:"26K",
        initialAmount:"5,000",
        finalAmount:"5,000,000"
    },
    {
        id: 1,
        stackText: "Arts & Theatre",
        heading: "FunnyBone Live 2024 - Aina's Son",
        location:"Eko Hotels & Suites",
        state:"Lagos",
        date:"Jul 16, 2024",
        time:"6:00 PM",
        rating:"3.7",
        numbers:"5,274",
        sold:"26K",
        initialAmount:"5,000",
        finalAmount:"5,000,000"
    },
    {
        id: 1,
        stackText: "Arts & Theatre",
        heading: "FunnyBone Live 2024 - Aina's Son",
        location:"Eko Hotels & Suites",
        state:"Lagos",
        date:"Jul 16, 2024",
        time:"6:00 PM",
        rating:"3.7",
        numbers:"5,274",
        sold:"26K",
        initialAmount:"5,000",
        finalAmount:"5,000,000"
    },
    {
        id: 1,
        stackText: "Arts & Theatre",
        heading: "FunnyBone Live 2024 - Aina's Son",
        location:"Eko Hotels & Suites",
        state:"Lagos",
        date:"Jul 16, 2024",
        time:"6:00 PM",
        rating:"3.7",
        numbers:"5,274",
        sold:"26K",
        initialAmount:"5,000",
        finalAmount:"5,000,000"
    },
    {
        id: 1,
        stackText: "Arts & Theatre",
        heading: "FunnyBone Live 2024 - Aina's Son",
        location:"Eko Hotels & Suites",
        state:"Lagos",
        date:"Jul 16, 2024",
        time:"6:00 PM",
        rating:"3.7",
        numbers:"5,274",
        sold:"26K",
        initialAmount:"5,000",
        finalAmount:"5,000,000"
    },
    {
        id: 1,
        stackText: "Arts & Theatre",
        heading: "FunnyBone Live 2024 - Aina's Son",
        location:"Eko Hotels & Suites",
        state:"Lagos",
        date:"Jul 16, 2024",
        time:"6:00 PM",
        rating:"3.7",
        numbers:"5,274",
        sold:"26K",
        initialAmount:"5,000",
        finalAmount:"5,000,000"
    },
    {
        id: 1,
        stackText: "Arts & Theatre",
        heading: "FunnyBone Live 2024 - Aina's Son",
        location:"Eko Hotels & Suites",
        state:"Lagos",
        date:"Jul 16, 2024",
        time:"6:00 PM",
        rating:"3.7",
        numbers:"5,274",
        sold:"26K",
        initialAmount:"5,000",
        finalAmount:"5,000,000"
    },
]