export const CreditBalanceData = [
    {
        id: 1,
        date: "Dec 1, 2024",
        description: "Bank transfer to ****2345 | First Bank of Nigeria",
        amount: -40000,
        category: "Payout",
        status: "Successful",
    },
    {
        id: 2,
        date: "Dec 4, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        category: "Refund",
        status: "Pending",
    },
    {
        id: 3,
        date: "Dec 7, 2024",
        description: "Ticket purchase for Afro Nation",
        amount: -40000,
        category: "Purchase",
        status: "Failed",
    },
    {
        id: 4,
        date: "Dec 1, 2024",
        description: "Bank transfer to ****2345 | First Bank of Nigeria",
        amount: -40000,
        category: "Payout",
        status: "Successful",
    },
    {
        id: 5,
        date: "Dec 1, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        category: "Purchase",
        status: "Pending",
    },
    {
        id: 6,
        date: "Dec 1, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        category: "Purchase",
        status: "Pending",
    },
    {
        id: 7,
        date: "Dec 1, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        category: "Refund",
        status: "Failed",
    },
    {
        id: 8,
        date: "Dec 1, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        category: "Payout",
        status: "Successful",
    },
    {
        id: 9,
        date: "Dec 1, 2024",
        description: "Bank transfer to ****2345 | First Bank of Nigeria",
        amount: -40000,
        category: "Payout",
        status: "Successful",
    },
    {
        id: 10,
        date: "Dec 4, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        category: "Refund",
        status: "Pending",
    },
    {
        id: 11,
        date: "Dec 7, 2024",
        description: "Ticket purchase for Afro Nation",
        amount: -40000,
        category: "Purchase",
        status: "Failed",
    },
    {
        id: 12,
        date: "Dec 1, 2024",
        description: "Bank transfer to ****2345 | First Bank of Nigeria",
        amount: -40000,
        category: "Payout",
        status: "Successful",
    },
    {
        id: 13,
        date: "Dec 1, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        category: "Purchase",
        status: "Pending",
    },
    {
        id: 14,
        date: "Dec 1, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        category: "Purchase",
        status: "Pending",
    },
    {
        id: 15,
        date: "Dec 1, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        category: "Refund",
        status: "Failed",
    },
    {
        id: 16,
        date: "Dec 1, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        category: "Payout",
        status: "Successful",
    },
]