export const eventData = [
    {
        id: 1,
        date: "Dec 1, 2024",
        description: "Bank transfer to ****2345 | First Bank of Nigeria",
        amount: -40000,
        event:"395879WD",
        name:"Davido Live In Concert",
        venue:"Eko Atlantic City, Lagos",

        category: "Payout",
        status: "Upcoming",
    },
    {
        id: 2,
        date: "Dec 4, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        event:"395879WD",
        name:"Davido Live In Concert",
        venue:"Eko Atlantic City, Lagos",

        category: "Refund",
        status: "Past",
    },
    {
        id: 3,
        date: "Dec 7, 2024",
        description: "Ticket purchase for Afro Nation",
        amount: -40000,
        event:"395879WD",
        name:"Davido Live In Concert",
        venue:"Eko Atlantic City, Lagos",

        category: "Purchase",
        status: "Cancelled",
    },
    {
        id: 4,
        date: "Dec 1, 2024",
        description: "Bank transfer to ****2345 | First Bank of Nigeria",
        amount: -40000,
        event:"395879WD",
        name:"Davido Live In Concert",
        venue:"Eko Atlantic City, Lagos",

        category: "Payout",
        status: "Upcomming",
    },
    {
        id: 5,
        date: "Dec 1, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        event:"395879WD",
        name:"Davido Live In Concert",
        venue:"Eko Atlantic City, Lagos",

        category: "Purchase",
        status: "Past",
    },
    {
        id: 6,
        date: "Dec 1, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        event:"395879WD",
        name:"Davido Live In Concert",
        venue:"Eko Atlantic City, Lagos",

        category: "Purchase",
        status: "Past",
    },
    {
        id: 7,
        date: "Dec 1, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        event:"395879WD",
        name:"Davido Live In Concert",
        venue:"Eko Atlantic City, Lagos",

        category: "Refund",
        status: "Cancelled",
    },
    {
        id: 8,
        date: "Dec 1, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        event:"395879WD",
        name:"Davido Live In Concert",
        venue:"Eko Atlantic City, Lagos",

        category: "Payout",
        status: "Upcomming",
    },
    {
        id: 9,
        date: "Dec 1, 2024",
        description: "Bank transfer to ****2345 | First Bank of Nigeria",
        amount: -40000,
        event:"395879WD",
        name:"Davido Live In Concert",
        venue:"Eko Atlantic City, Lagos",

        category: "Payout",
        status: "Upcomming",
    },
    {
        id: 10,
        date: "Dec 4, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        event:"395879WD",
        name:"Davido Live In Concert",
        venue:"Eko Atlantic City, Lagos",

        category: "Refund",
        status: "Past",
    },
    {
        id: 11,
        date: "Dec 7, 2024",
        description: "Ticket purchase for Afro Nation",
        amount: -40000,
        event:"395879WD",
        name:"Davido Live In Concert",
        venue:"Eko Atlantic City, Lagos",

        category: "Purchase",
        status: "Cancelled",
    },
    {
        id: 12,
        date: "Dec 1, 2024",
        description: "Bank transfer to ****2345 | First Bank of Nigeria",
        amount: -40000,
        event:"395879WD",
        name:"Davido Live In Concert",
        venue:"Eko Atlantic City, Lagos",

        category: "Payout",
        status: "Upcomming",
    },
    {
        id: 13,
        date: "Dec 1, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        event:"395879WD",
        name:"havido Live In Concert",
        venue:"Eko Atlantic City, Lagos",

        category: "Purchase",
        status: "Past",
    },
    {
        id: 14,
        date: "Dec 1, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        event:"395879WD",
        name:"Davido Live In Concert",
        venue:"Eko Atlantic City, Lagos",

        category: "Purchase",
        status: "Past",
    },
    {
        id: 15,
        date: "Dec 1, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        event:"395879WD",
        name:"Davido Live In Concert",
        venue:"Eko Atlantic City, Lagos",

        category: "Refund",
        status: "Cancelled",
    },
    {
        id: 16,
        date: "Dec 1, 2024",
        description: "Ticket refund from Davido Live In Concert",
        amount: -40000,
        event:"395879WD",
        name:"Davido Live In Concert",
        venue:"Eko Atlantic City, Lagos",

        category: "Payout",
        status: "Upcomming",
    },
]